# Generated by Django 2.0.6 on 2018-06-10 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2ex', '0003_auto_20180610_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatar',
            new_name='avatar_hash',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AlterField(
            model_name='topic',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 10, 22, 39, 21, 321812)),
        ),
    ]
