# Generated by Django 2.0.6 on 2018-06-10 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2ex', '0004_auto_20180610_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='Tag',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='topic',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 10, 23, 6, 42, 620077)),
        ),
    ]
